### ISSUE TITLE
Crash after using lifeline

### ISSUE THREAD

**Issue by JRHorse** [Maerciez/TheMillionaireGame#60]
Hello, I am really enjoying this as the user interface is a lot friendlier than other projects I've seen!
I want to report an error where, after using lifelines and advancing to a question, the program crashes.
Specifically, I triggered "ask the host" on question 11 (third of four available lifelines). After the answer was revealed and I attempted to click on "Question" to advance to question 12, the program crashed.

Error messages are as follows:

> Faulting application name: MillionaireGame.exe, version: 1.1.684.0, time stamp: 0x656a6912
> Faulting module name: KERNELBASE.dll, version: 10.0.22621.2715, time stamp: 0xcc3ea002
> Exception code: 0xe0434352
> Fault offset: 0x00149132
> Faulting process id: 0x0x3EAC
> Faulting application start time: 0x0x1DA265D1FFCD070
> Faulting application path: D:\MillionaireGame_v1.1.684\MillionaireGame.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 8816b4fa-ccf6-4f8c-ae07-fc1a1906d82b
> Faulting package full name: 
> Faulting package-relative application ID: 
> 
> Application: MillionaireGame.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Runtime.InteropServices.COMException
>    at WMPLib.WindowsMediaPlayerClass.get_controls()
>    at MillionaireGame.Sounds.StopAudio(System.String, Int32)
>    at MillionaireGame.Question+_Closure$__._Lambda$__8-11()
>    at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.ThreadHelper.ThreadStart()

**Comment by Macronair** [comment]
I took this issue with the developement for 1.2 where a lot of issues are fixed.
Did you got the error message again after this?

**Comment by ristoryti** [comment]
At least for me the other lifelines work but phone a friend always crashes the program either on first or second press of the lifeline button.

**Comment by matt3756-tech** [comment]
Crashing randomly for me too on latest version 1.2.

Sometimes it don't happen for several games, other times back to back. My program just closes when I click a lifeline sometimes, no errors or anything.
